baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "thesoundofemotion.com" # the base hostname & protocol for your site.
title: "The Sound of Emotion"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "test1"  #Add your github url here.
twitter: ""  #Add your twitter url here.


gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "share-btns.html"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
provider : google
google :
tracking_id : 'UA-39472119-1'
getclicky :
site_id :
